[package]
name = "my-redis"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"
anyhow = "1"
atoi = "3"
clap = { version = "4", features = ["derive"] }
thiserror = "2.0.21"

[[bin]]
name = "my-mini-redis-cli"
path = "src/bin/client.rs"
